### PR TITLE
Add Lombok support

### PR DESCRIPTION
**Pull request by kelloggm**
This pull request adds inference of `@This` annotations for Lombok builders.

It also refactors the AutoValue code so that what can be shared between the two, is.

The expectation is that this code will only work on code that has been [delombok'd](https://projectlombok.org/features/delombok). Support for automatic delombok'ing will need to be written for each build system, but this code provides the basic support.

This PR's tests only ensure that the code doesn't crash. A follow-on PR to github.com/kelloggm/typesafe-builder-checker will include tests that will fail without this PR; however, I cannot think of a good way to test this here, and that appears to be the way the AutoValue tests are structured, too.

I know that I made a few changes to whitespace/imports throughout the code I was editing; I apologize for the moderately annoying diff, but I suggest including an automated tool to enforce code style in the future to avoid such changes.

### CODE REVIEW

**Comment by kelloggm** [comment]
@ranmanli @msridhar I don't have the ability to request reviewers here, but I'd appreciate reviews from you both

**Review by msridhar — APPROVED** [review]

**Comment by msridhar** [comment]
Looks great!

**Comment by msridhar** [comment]
Oops, I already merged this, but @ranmanli please look this over and if you notice any issues write a comment

**Comment by ranmanli** [comment]
Sure I will.

Regards,
Manli Ran

________________________________
发件人: Manu Sridharan <notifications@github.com>
发送时间: Wednesday, June 26, 2019 6:59:43 PM
收件人: msridhar/returnsrecv-checker
抄送: ranmanli; Mention
主题: Re: [msridhar/returnsrecv-checker] Add Lombok support (#2)


Oops, I already merged this, but @ranmanli<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Franmanli&data=02%7C01%7C%7C9bb0f84a1ea74f3ada5208d6faa31fee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636971975851663853&sdata=urkq%2FOKF3MJeF0N3T8NExAwNjRFSmxZv9Oo2gqpO%2BXc%3D&reserved=0> please look this over and if you notice any issues write a comment

―

**Comment by ranmanli** [comment]
It looks good:)

**Pull request merged**
